#main.exe: main.cpp makefile
#	g++ main.cpp -g -o main.exe -I"D:/cpp_libraries/glfw-3.3.5-source/include" -I"D:/cpp_libraries/glew-2.1.0-source/include" -L"D:/cpp_libraries/glfw-3.3.5-compiled/src" -L"D:/cpp_libraries/glew-2.1.0-compiled/lib" -lglfw3 -lglew32 -lopengl32

main: main.cpp makefile
	g++ main.cpp -g -o main -lglfw -lGL -lX11 -lGLEW -std=c++2a
